/**
 * The Content script runs in each Chrome tab, it is responsible for:
 *  - connecting to the background script and routing events to/from it
 *  - injecting the fdc3 api into each tab
 *  - rendering the intent resolver UI
 *  
 */
import channels from "./system-channels";
import utils from "./utils";
import {Listener as fdc3Listener} from './types/fdc3/Listener';
import {fdc3Event} from './types/FDC3Event';
import {FDC3Event} from './types/FDC3Event';
import {FDC3Message} from './types/FDC3Message';
import {IntentMetadata} from './types/fdc3/IntentMetadata';
import {AppIntent} from './types/fdc3/AppIntent';
import {Context} from './types/fdc3/Context';
import {AppInstance, InstanceTypeEnum} from './types/AppInstance';


//establish comms with the background script 
const port = chrome.runtime.connect({name: "fdc3"});

//flag to indicate the background script is ready for fdc3!
let connected = false;



//queue of pending events - accumulate until the background is ready
const eventQ : Array<FDC3Message> = [];


/**
 * return listeners
 * most fdc3 api calls are promise based and many require resolution/rejection following complex interaction that may involve end user input, app loading times etc
 * so, we need to a symetrical return event when events are dispatched to the background script and to uniquely identifiy the event
 * also, need to support timeout/expiration of the event, for example, if an app takes too long to load or an end user never responds to a prompt
 * 
 * all promise based FDC3 methods send an event to the background script and listens for an event of "return" + eventName 
 * a unique identifier is assigned to the event (timestamp) 
 * the return handler will route back to correct handler function via the timestamp identifier
 * handlers will be routinely cleaned up by finding all events that have expired (check timestamp) and rejecting those items
 */
//collection of listeners for api calls coming back from the background script
const returnListeners : Map<string,any> = new Map();
const returnTimeout = (1000 * 60 * 2);

 //listen for return messages for api calls
 port.onMessage.addListener(msg => {
    //is there a returnlistener registered for the event?
    let listener = returnListeners.has(msg.topic) ? returnListeners.get(msg.topic).listener : null;
    if (listener){
        listener.call(port,msg);
        returnListeners.delete(msg.name);
    }
 });

 //automated handlers based on manifest metadata - other handlers are set and dispatched by the API layer
 //these just need to be markers - since the handling itself is just autogenerated from the metadata held in the manifest 
const _intentHandlers : Array<string> = []; 
const  _contextHandlers : Array<string> = [];
let contentActions : any = null;
let contentName : string = null;
let currentChannel : string = null;

 //retrieve the document title for a tab
const getTabTitle = (tabId : number) : Promise<string> => {
    let id = tabId;
    return new Promise((resolve, reject) => {
        port.onMessage.addListener(msg => {
            if (msg.topic === "tabTitle" && id === msg.tabId){
                resolve(msg.data.title);
            }
        });
        port.postMessage({topic:"getTabTitle", "tabId":tabId});
    });  
};


const wireTopic = (topic : string, config?: any) : void => {
    
    document.addEventListener(`FDC3:${topic}`,(e : FDC3Event) => {
        const cb = config ? config.cb : null;
        const isVoid = config ? config.isVoid : null;

        //get eventId and timestamp from the event 
        if (! isVoid){
            const eventId : string = e.detail.eventId;
            
            returnListeners.set(eventId, {
                ts:e.ts,
                listener:function(msg : FDC3Message, port : chrome.runtime.Port){
                document.dispatchEvent(fdc3Event(`FDC3:return_${eventId}`, msg.data)); }
            });
            if (cb){
                cb.call(this,e);
            }
        }
        //if  background script isn't ready yet, queue these messages...
        const msg : FDC3Message = {topic:topic,  data:e.detail};
        if (!connected){
            eventQ.push(msg);
        }
        else {
            port.postMessage(msg);   
        }
    }); 
    
};
 
 //listen for FDC3 events
 const topics = ["open","raiseIntent","addContextListener","addIntentListener","findIntent","findIntentsByContext","getCurrentContext","getSystemChannels","getOrCreateChannel", "getCurrentChannel"];
 topics.forEach(t => {wireTopic(t);});
 //set the custom ones...
 wireTopic("joinChannel",{cb:(e : FDC3Event) => { currentChannel = e.detail.channel;}});
 wireTopic("leaveCurrentChannel",{cb:(e : FDC3Event) => { currentChannel = "default";}});
 wireTopic("broadcast",{isVoid:true});
 wireTopic("dropContextListener",{isVoid:true});
 wireTopic("dropIntentListener",{isVoid:true});

document.addEventListener("FDC3:resolver-close", e => {
    port.postMessage({topic:"resolver-close"});   
    if (resolver){
        resolver.style.display = "none";
    }
});

//systemchannels are constant and we don't have to go to the background script, so handle directly
//document.addEventListener("FDC3:getSystemChannels", e => {
 //   document.dispatchEvent(new CustomEvent("FDC3:returnSystemChannels",{detail:{data:channels} } ));
//});

const actionUrl = async(data : any) : Promise<string> => {
    return new Promise(async (resolve, reject) => {
        const directoryUrl : string= await utils.getDirectoryUrl();
        const body : any = {"context":data.context};
        if (data.intent){
            body.intent = data.intent;
        }
        const templateR = await fetch(`${directoryUrl}/apps/${contentName}/action`,{method:"POST",body:JSON.stringify(body)});
        resolve(await templateR.text());
    });
};

port.onMessage.addListener(async (msg) => {
     
    
    if (msg.topic === "environmentData"){
        console.log("app connected", msg.data, eventQ);
        //we're now ready for general fdc3 comms with the background
        connected = true;
        //if there is a queue of pending events, then act on them, these will mostly be addContext/addIntent Listener calls
        eventQ.forEach(e => {
            port.postMessage(e); 
        });

        //is there actions meta data defined? If so, wire up listeners if intents and context metadata are there
        const mani = msg.data.directory ? msg.data.directory.actions : null;
        //set globals
        contentName = msg.data.directory ? msg.data.directory.name : null;
        contentActions = mani;
        //if there is action metadata for the app in the directory - set up intent & context handlers
        if (mani){
            //generate a guid for the listener
            //this would normally come from the api layer in the dom...
            const guid = utils.guid();
            if (mani.intents){
                //iterate through the intents, and set listeners
                mani.intents.forEach((intent : any) => {
                    port.postMessage({topic:"addIntentListener", "data": {id: guid, intent:intent.intent }}); 
                    _intentHandlers.push(intent.intent);
                });
            }
            if (mani.contexts){
                //iterate through context metadata and set listeners
                mani.contexts.forEach((context : Context) => {
                    port.postMessage({topic:"addContextListener", "data": {id: guid, context:context.type}}); 
                    _contextHandlers.push(context.type);
                });
            
            }
        }
        if (msg.data.currentChannel){
            currentChannel = msg.data.currentChannel;
            //re-join the channel but don't get the current context - since we are reloading or navigating 
            port.postMessage({topic:"joinChannel", "data": {channel:currentChannel, restoreOnly:true}});      
        }
    }
   else  if (msg.topic === "context"){
       //check for handlers at the content script layer (automatic handlers) - if not, dispatch to the API layer...
       let contextSent = false;
       if (msg.data && msg.data.context){
            if (_contextHandlers.indexOf(msg.data.context.type) > -1 && contentActions){
        
                const ctxUrl = await actionUrl(msg.data);
                //don't reload if they are the same...
                //don't redirect if url is empty (i.e. nothing found for the action)
                if (ctxUrl && window.location.href !== ctxUrl){
                    window.location.href = ctxUrl; 
                    contextSent = true;
                }
                //focus the actual tab
                //window.focus();
            }
            if (!contextSent) {   
                document.dispatchEvent(new CustomEvent("FDC3:context",{
                    detail:{data:msg.data}
                }));
            }
        }

       
    }
    else if (msg.topic === "intent") {
        let intentSent = false;
        //check for handlers at the content script layer (automatic handlers) - if not, dispatch to the API layer...
        if (_intentHandlers.indexOf(msg.data.intent) > -1 && contentActions){
         
            const intUrl : string = await actionUrl(msg.data);
            //don't reload if they are the same...
            if (intUrl && window.location.href !== intUrl){
                window.location.href = intUrl; 
                intentSent = true;
            }
           // window.focus();
        }
        if (!intentSent){
            document.dispatchEvent(new CustomEvent("FDC3:intent",{
                detail:{data:msg.data}
            })); 
        }
    }
    else if (msg.topic === "setCurrentChannel"){
        if (msg.data.channel){
            currentChannel = msg.data.channel;
        }
    }

});

let resolver : HTMLElement = null;

 document.addEventListener('keydown', k => {
     if (k.code === "Escape" ){
        document.dispatchEvent(new CustomEvent("FDC3:resolver-close",{
        })); 
       /* if (resolver){
            resolver.style.display = "none";
        }*/
    }
});

 
 //handle click on extension button
 //raise directory search overlay
 chrome.runtime.onMessage.addListener(
    function(request, sender, sendResponse) {
        if (request.message === "get-tab-title"){
            sendResponse(document.title);
        }
        else if (request.message === "popup-get-current-channel"){
            sendResponse(currentChannel);
        }
        else if (request.message === "popup-join-channel"){
            currentChannel = request.channel;
            port.postMessage({topic:"joinChannel", "data": {channel:request.channel}}); 
        }
        else if (request.message === "popup-open"){
            port.postMessage({topic:"open", "data": {name:request.name, autojoin:true}}); 
        }
  
      else if (request.message === "intent_resolver"){
        if (! resolver){
            resolver = createResolverRoot();
            document.body.appendChild(resolver);
        }
        resolver.style.display = "block";
        //resolve the intent name to the display name for the intent - by looking it up in the data response
        let dName : string = null;
        request.data.forEach((item : any )=> {
            if (!dName && Array.isArray(item.details.directoryData.intents)){
                item.details.directoryData.intents.forEach((intent : any) => {
                    if(intent.name === request.intent){
                        dName = intent.display_name;
                    }
                });
            }
        } );
        const header : Element = resolver.shadowRoot.querySelectorAll("#resolve-header")[0];
        header.textContent = `Intent '${(dName ? dName : request.intent)}'`;
        let list = resolver.shadowRoot.querySelectorAll("#resolve-list")[0];
        list.innerHTML = "";

        //contents
        //item represents an app...
        request.data.forEach((item : AppInstance) => {
            const selected = item;
            const tab : chrome.tabs.Tab = item.details && item.details.port ? item.details.port.sender.tab : null;
            const data = item.details.directoryData ? item.details.directoryData : null;
            const rItem : Element = document.createElement("div");

            rItem.className = "item";
            const title = data ? data.title : "Untitled";
            const iconNode : Element = document.createElement("img");
            iconNode.className = "icon";
            rItem.appendChild(iconNode);
            const titleNode : Element = document.createElement("span");
            rItem.appendChild(titleNode);
            //title should reflect if this is creating a new window, or loading to an existing one
            if (item.type === InstanceTypeEnum.Window){
                
               // let icon = document.createElement("img");
               // icon.className = "icon"; 
                if (tab.favIconUrl){
                    iconNode.setAttribute("src", tab.favIconUrl);
                }
                //rItem.appendChild(icon);
                //titleNode = document.createElement("span");
                titleNode.id = "title-" + tab.id;
                titleNode.textContent = title;
                titleNode.setAttribute("title", `${title} (${tab.url})`);
                const query : string = "#title-" + tab.id;
                
                //async get the window title
                getTabTitle(tab.id).then((t : string )=> { 
                    let titles =  list.querySelectorAll(query);
                    if (titles.length > 0 && t.length > 0){
                        titles[0].textContent = t;
                        titles[0].setAttribute("title",`${t} (${tab.url})`);
                    }
                });
            }
            else {
                if (data && data.icons && data.icons.length > 0){
                    iconNode.setAttribute("src", data.icons[0].icon);
                }
            }
            if (titleNode){
                if (titleNode.textContent.length === 0){
                    titleNode.textContent = title;
                }
                if (titleNode.getAttribute("title").length === 0){
                    titleNode.setAttribute("title",(data ? data.start_url : (tab ? tab.title : "Untitled")));
                }
                
            }
            rItem.addEventListener("click",evt => {
                //send resolution message to extension to route
                port.postMessage({
                    topic:request.eventId,
                    intent:request.intent,
                    selected:selected,
                    context:request.context
                }); 
                list.innerHTML = "";
                resolver.style.display = "none";
            });
            list.appendChild(rItem);
        });
      }

    }
    
  );

  function createResolverRoot() : HTMLElement{
 
        // Create root element
        const root : HTMLElement= document.createElement('div');
        const wrapper : HTMLElement = document.createElement('div');
        wrapper.id = "fdc3-intent-resolver";

         // Create a shadow root
         const shadow : ShadowRoot = root.attachShadow({mode: 'open'});

        // Create some CSS to apply to the shadow dom
        const style : Element= document.createElement('style');

        style.textContent = `
        #fdc3-intent-resolver {
            width:400px;
            height:400px;
            margin-left:-200px;
            margin-top:-200px;
            left:50%;
            top:50%;
            background-color:#444;
            position:absolute;
            z-index:9999;
            font-family:sans-serif;
            filter: drop-shadow(6px 4px 1px #969696);
            border-radius: 10px;
   
        }

        #resolve-header {
            height:25px;
            color:#eee;
            font-size: 18px;
            width: 100%;
            text-align: center;
            padding-top: 10px;
        }
        
        #resolve-subheader {
            height:20px;
            color:#eee;
            font-size: 16px;
            width: 100%;
            text-align: center;
        }
        #resolve-list {
            height:300px;
            overflow:scroll;
            margin:10px;
            font-size:14px;
            border-radius: 3px;
            margin: 3px;
            border: #333;
            background-color: #555;
        }
        
        #resolve-list .item {
            color:#fff;
            flexFlow:row;
            height:20px;
            padding:3px;
            overflow:hidden;
        }


        #resolve-list .item .icon {
           height:20px;
           padding-right:3px;
        }
        
        #resolve-list .item:hover {
            background-color:#999;
            color:#ccc;
            cursor: pointer;
        }
        `;
        const header : HTMLElement = document.createElement('div');
        header.id = "resolve-header";
        wrapper.appendChild(header);
        const subheader : HTMLElement = document.createElement('div');
        subheader.id = "resolve-subheader";
        subheader.textContent = "choose an app";
        wrapper.appendChild(subheader);
        const list : HTMLElement = document.createElement('div');
        list.id = "resolve-list";
        wrapper.appendChild(list);
        
        // Attach the created elements to the shadow dom
        shadow.appendChild(style);
        shadow.appendChild(wrapper);
        

      
        return root;
    }
  

  //inject the FDC3 API
  const s : Element = document.createElement('script');
  s.setAttribute("src", chrome.extension.getURL('api.js'));
  
  (document.head||document.documentElement).appendChild(s);